Shlemen kirill/create tables and views
Dev-incubator/DIMS-Core.Double pull request #1
Opened 2020-12-18 09:23 UTC by ShlemenKirill

Create tables, views, procedures by Admin and Member roles.

2020-12-19 09:06 UTC, PushMeNow requested changes
Hi dude.
I left some comment. Fix them and let me know.

2020-12-19 09:06 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserProgress.sql
> +    ON UserTask.UserTaskId = TaskTrack.TaskTrackId
You will still need Task table. Could you leave a comment about it?

2020-12-19 09:06 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserProgress.sql
> +    UserProfiles.FirstName AS UserName,
Here UserName is First and Last names together :)

2020-12-19 10:08 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskState.sql
> +	[StateName] NVARCHAR(50) NOT NULL
I fixed it
```suggestion
[StateName] NVARCHAR(10) NOT NULL
```

2020-12-19 10:10 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTrack.sql
> +	FOREIGN KEY (UserTaskId) REFERENCES TaskState(StateId)
I fixed it
```suggestion
	FOREIGN KEY (UserTaskId) REFERENCES TaskState(StateId)
	FOREIGN KEY (UserTaskId) REFERENCES UserTask(UserTaskId)
```

2020-12-19 10:12 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Tables/UserTask.sql
> +	FOREIGN KEY (UserId) REFERENCES TaskTrack(TaskTrackId)
```suggestion
FOREIGN KEY (UserId) REFERENCES UserProfiles(UserId)
```

2020-12-19 10:13 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserProgress.sql
> +    ON UserTask.UserTaskId = TaskTrack.TaskTrackId
```suggestion
--INNER JOIN [TASK]
--ON UserTask.UserTaskId = Task.TaskId 
```

2020-12-19 10:18 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserProgress.sql
> +    UserProfiles.FirstName AS UserName,
```suggestion
 UserProfiles.FirstName AS UserName,
 (UserProfiles.FirstName + ' ' + UserProfiles.LastName) AS UserName,
```

2020-12-19 10:23 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Tables/TaskTrack.sql
> +	[TrackNote] INT NOT NULL
```suggestion
    [TrackNote] NVARCHAR(100) NULL
```

2020-12-19 11:01 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/SetUserTaskAsFail.sql
> +	VALUES ('Fail')
Maybe this code is right?)
```suggestion
	UPDATE UserTask
	SET StateId = (
	SELECT StateId FROM TaskState
	WHERE [TaskState].StateName = 'Success'
	)
	WHERE [UserTask].TaskId = @TaskId AND [UserTask].UserId = @UserId
```

2020-12-19 11:02 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteUser.sql
> +RETURN 0
I need to delete line 8?

2020-12-21 14:51 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteUser.sql
> +RETURN 0
Yeap, you have to. Usually procedure shouldn't have returning value.

2020-12-21 14:56 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/SetUserTaskAsFail.sql
> +	VALUES ('Fail')
> else insert record with UserId, TaskId and StateId

I don't this code.

2020-12-21 15:59 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteUser.sql
> +RETURN 0
> Yeap, you have to. Usually procedure shouldn't have returning value.
I changed the code

2020-12-21 16:01 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/SetUserTaskAsFail.sql
> +	VALUES ('Fail')
```suggestion
	CREATE PROCEDURE [dbo].[SetUserTaskAsFail]
	@UserId int,
	@TaskId int
AS
	UPDATE UserTask
	SET StateId = 3
	WHERE [UserTask].TaskId = @TaskId AND [UserTask].UserId = @UserId
```

2020-12-21 20:02 UTC, Andrey-Gvozdev approved these changes

2020-12-23 07:43 UTC, PushMeNow requested changes
Hi man!
I did a comment. You have inaccuracy in condition of IF statement.

2020-12-23 07:43 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/SetUserTaskAsFail.sql
> +	AND EXISTS (SELECT TaskId FROM UserTask	WHERE [UserTask].TaskId = @TaskId))
You have to join these conditions in one: 
`WHERE UserId = {smth} AND TaskId = {smth}`

2020-12-23 16:28 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/SetUserTaskAsFail.sql
> +	AND EXISTS (SELECT TaskId FROM UserTask	WHERE [UserTask].TaskId = @TaskId))
IF EXISTS (SELECT UserId FROM UserTask	WHERE [UserTask].UserId = @UserId AND [UserTask].TaskId = @TaskId)

2020-12-23 19:39 UTC, PushMeNow approved these changes
Approve

2020-12-23 19:40 UTC, merged