Andrey gvozdev/scaffolding
Dev-incubator/DIMS-Core.Double pull request #10
Opened 2020-12-27 10:36 UTC by Andrey-Gvozdev

2020-12-27 10:47 UTC, ShlemenKirill approved these changes

2020-12-27 10:57 UTC, PushMeNow requested changes
I did some comments. Fix them and let me know

2020-12-27 10:57 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vUserTask.sql
> +	UserTask.UserId AS UserID,
Don't use 'ID' at the end please. Just 'Id'.

2020-12-27 10:57 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/DIMSCoreContext.cs
> +        public virtual DbSet<VUserTrack> VUserTrack { get; set; }
All these props must be in plural form.

2020-12-27 10:57 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Models/DIMSCoreContext.cs
> +        }
This setting exists in database json. Remove it.

2020-12-29 17:41 UTC, PushMeNow approved these changes
Approve

2020-12-29 17:53 UTC, merged