Add unit tests for repositories
Dev-incubator/DIMS-Core.Double pull request #10
Opened 2021-03-06 18:32 UTC by STALINovsky

Add class to assist in testing repositories & implement TaskStateRepositoryTest, TaskTrackRepositoryTest.

2021-03-06 19:38 UTC, ArtyomKolosov2 requested changes
Hi. I did some comments on your PR. Some of your namings in tests aren't obvious as for me. Please, improve them.

2021-03-06 19:41 UTC, ArtyomKolosov2 commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Infrastructure/RepositoryTestHelper.cs
> +        public async Task IsEntityUpdated(TEntity startEntityState, Func<TEntity, TEntity> changeState)
Why this method called "IsEntityUpdated", but it doesn't returns boolean value?

2021-03-06 19:43 UTC, ArtyomKolosov2 commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Infrastructure/RepositoryTestHelper.cs
> +        public async Task GetAllEqualsSeedData(ICollection<TEntity> seedData)
This naming looks quite strange

2021-03-12 09:05 UTC, PushMeNow commented
@STALINovsky I'm closing this PR because there are too many marks which need to fix. You are using incorrect approach for testing. Contact with @dbogdan2000 he will explain what is incorrect and how to write correct test.

2021-03-12 09:05 UTC, closed without merging