Tests
Dev-incubator/DIMS-Core.Double pull request #11
Opened 2021-03-16 14:06 UTC by dbogdan2000

Added unit tests for TaskRepository and DirectionRepository.

2021-03-17 19:25 UTC, PushMeNow requested changes
Hi man!
I did some comments. Let me know if any questions.

2021-03-17 19:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/DirectionRepositoryTest.cs
> +            var directionRepository = new DirectionRepository(context);
Let's refactor it. Move whole necessary initialization in separate fixture as I showed you.

2021-03-17 19:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/DirectionRepositoryTest.cs
> +                                         };
Move data seeding in fixture too

2021-03-17 19:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/DirectionRepositoryTest.cs
> +            Assert.Equal(directions.Count, await result.CountAsync());
So when you create separate fixture you have to compare exact count.
Example:
<code>
   Assert.Equal(1, await result.CountAsync())
</code>
You mustn't use context directly.

2021-03-17 19:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/DirectionRepositoryTest.cs
> +            var result = await directionRepository.GetById(1);
You have to remember Id in fixture class and put it here.

2021-03-17 19:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/DirectionRepositoryTest.cs
> +            await Assert.ThrowsAsync<ArgumentException>(() => directionRepository.GetById(2));
Hmm... Why here are you checking ArgumentException? Here should be EntityNotExistException

2021-03-17 19:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/DirectionRepositoryTest.cs
> +            Assert.Equal(await result.CountAsync(), directions.Count + 1);
I don't see the reason to check records count in context. It is not main goal of test for creating.

2021-03-17 19:25 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/DirectionRepositoryTest.cs
> +                               .Description);
Again I don't see the reason to check it. Currently you have to chek result from Update method.

2021-03-24 19:45 UTC, PushMeNow requested changes
Hi!
So it looks like better. Fix pls some little missed comments and I'll approve PR.

2021-03-24 19:45 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/DirectionRepositoryTest.cs
> +
Arrange?

2021-03-24 19:45 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/DirectionRepositoryTest.cs
> +            Assert.NotNull(await _fixture.Context.Directions.FindAsync(_fixture.DeleteDirectionId));
Wait what? Why NotNull?

2021-03-24 19:45 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Fixtures/BaseRepositoryFixture.cs
> +
Too many emapty spaces

2021-03-24 19:45 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/TaskRepositoryTest.cs
> +            var newTask = new Task
Arrange?

2021-03-24 19:45 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/TaskRepositoryTest.cs
> +            var updatedName = "Updated Name";
Arrange?

2021-03-24 19:45 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/TaskStateRepositoryTest.cs
> +            var updatedStateName = "Updated Name";
Arrange

2021-03-25 18:21 UTC, PushMeNow approved these changes
GJ! Approved

2021-03-26 07:31 UTC, ArtyomKolosov2 approved these changes
LGTM. Approved!

2021-03-26 07:32 UTC, merged