Gvozdev Andrey/RepositoryTasks
Dev-incubator/DIMS-Core.Double pull request #12
Opened 2020-12-29 21:11 UTC by Andrey-Gvozdev

Complete Repository tasks

2020-12-30 17:07 UTC, maximsan requested changes
Hello! I left some notes. Go through them please.

2020-12-30 17:07 UTC, maximsan commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
>                  // throw new AnyException(string paramName);
It's recommended to delete task description if it's done

2020-12-30 17:07 UTC, maximsan commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            return Task.Run(() => _context.Find<TEntity>(id));
We don't need `Task.Run` here. Return the result.

2020-12-30 17:07 UTC, maximsan commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            await Task.Run(() => _context.Entry(entity).State = EntityState.Modified);
We don't need `Task.Run` here.

2020-12-30 17:07 UTC, maximsan commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            });
We don't need `Task.Run` here.

2020-12-30 22:20 UTC, PushMeNow requested changes
Hi.
I did some comment. Fix them please. Let me know if any questions.

2020-12-30 22:20 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Common/Exceptions/IsCantBeNullException.cs
> +    public class IsCantBeNullException : BaseException
Incorrect name. Name of exception should portray "Why did exception happen?". Example, if object is null we have to throw exception so name for it ObjectNullException, ObjectNotFoundException, VariableNullException etc.

2020-12-30 22:20 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Common/Exceptions/IsCantBeZiroException.cs
> +    public class IsCantBeZiroException : BaseException
Same case, incorrect name

2020-12-30 22:20 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            return Task.Run(() => _context.Find<TEntity>(id));
Actually you can use async version of Find function and use await keyword without Task.Run

2020-12-30 22:20 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            return _set;
Usually here need to add AsNoTracking ending. You can read about it here https://metanit.com/sharp/entityframework/4.8.php

2020-12-31 12:53 UTC, maximsan requested changes
I left a bunch of notes. Please, go through carefully.

2020-12-31 12:53 UTC, maximsan commented on DIMS-Core/DIMS-Core.Common/Exceptions/ObjectZeroException.cs
> +        private readonly string ParamName;
Field names are camelCase in .net.  Please, read about naming convention.

2020-12-31 12:53 UTC, maximsan commented on DIMS-Core/DIMS-Core.Common/Exceptions/ParamCantBeNullException.cs
> +        private readonly string MethodName;
The same case is here

2020-12-31 12:53 UTC, maximsan commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +                throw new ObjectZeroException("Error. Id can't be zero.","id");
Why are your params in both errors in different order ?

2020-12-31 12:53 UTC, maximsan commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            await update;
I believe it can be done without `new Task and lambda expression`

2020-12-31 12:53 UTC, maximsan commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            return delete;
I believe it can be done without `new Task and lambda expression`. Don't need to be explicit about the return type, compiler can infer it. `var` is enough. Please, use sensible names for variables. Read about proper naming in programming if you don not know what is right.

2021-01-02 16:08 UTC, ShlemenKirill approved these changes

2021-01-02 18:08 UTC, PushMeNow requested changes
Hi.
I did some comments. Fix them please

2021-01-02 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            var entity = _context.Find<TEntity>(id);
Use _set field. Use async version of Find method

2021-01-02 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            return await _context.FindAsync<TEntity>(id);
I don't understand why do you call it here?

2021-01-02 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            await _context.AddAsync(entity);
Use _set

2021-01-02 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            _context.Entry(entity).State = EntityState.Modified;
Use _set

2021-01-02 18:08 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            _context.Remove(entity);
Use _set

2021-01-03 15:23 UTC, PushMeNow requested changes
Hi.
I did some comment. Fix them pls.

2021-01-03 15:23 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            return await _set.FindAsync(id);
Again ask: why do you use it if you did same above?

2021-01-03 15:23 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            _context.SaveChanges();
Not need

2021-01-03 15:23 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            await _context.SaveChangesAsync();
Not need

2021-01-03 15:23 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +            return _context.SaveChangesAsync();
Not need

2021-01-03 19:08 UTC, PushMeNow approved these changes
Approve

2021-02-14 15:09 UTC, closed without merging