Dto objects, business services
Dev-incubator/DIMS-Core.Double pull request #14
Opened 2021-04-05 16:04 UTC by ArtyomKolosov2

2021-04-05 17:41 UTC, dbogdan2000 approved these changes

2021-04-05 18:32 UTC, PushMeNow requested changes
Hi!
I did some comments. Let me know if any questions.

2021-04-05 18:32 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IDirectionService.cs
> +        public bool NotEqual(DirectionModel directionModel1, DirectionModel directionModel2);
Hmm... Why do you need it?

2021-04-05 18:32 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Interfaces/IUserProfileService.cs
> +        public bool NotEqual(UserProfileModel userModel1, UserProfileModel userModel2);
Again don't see the reason

2021-04-05 18:32 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/ReadOnlyService.cs
> +        protected ReadOnlyService(TRepository repository, IUnitOfWork unitOfWork, IMapper mapper)
Choose pls what will you use repo or UoW. Don't use both ways

2021-04-05 18:32 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/Service.cs
> +
Empty spaces

2021-04-07 19:45 UTC, PushMeNow requested changes
Some comments for you, dude)

2021-04-07 19:45 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/ReadOnlyService.cs
> +            if (_repository is Repository<TEntity> abstractRepository)
As I told need to add disposable behaviour to IRepository and IReadOnlyRepository

2021-04-07 19:45 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.BusinessLayer/Services/Service.cs
> +            await _unitOfWork.SaveChanges();
You don't need UoW for saving action. You can add it in base repository class

2021-04-11 20:47 UTC, PushMeNow approved these changes
Approved

2021-04-11 20:47 UTC, merged