Gvozdev Andrey/create repositories
Dev-incubator/DIMS-Core.Double pull request #14
Opened 2020-12-31 02:23 UTC by Andrey-Gvozdev

2021-01-02 17:53 UTC, PushMeNow approved these changes
Approve

2021-01-04 04:40 UTC, ShlemenKirill approved these changes

2021-01-05 08:42 UTC, PushMeNow requested changes
Hi.
Need improvement. Read my comment.

2021-01-05 08:42 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/VUserTrackRepository.cs
> +        public IQueryable<VUserTrack> GetAll() => _context.VUserTracks;
Could you create common base repository class for IReadOnlyRepository? Because you duplicate same logic in many classes. Look at Repository class.

2021-02-14 15:09 UTC, closed without merging