Create UserProfileRepository tests
Dev-incubator/DIMS-Core.Double pull request #16
Opened 2021-01-03 17:55 UTC by ShlemenKirill

2021-01-03 19:06 UTC, PushMeNow requested changes
Hi.
I did some comments. Fix them pls.

2021-01-03 19:06 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +        private IRepository<UserProfile> _userProfileRepository;
It is bad practice because in each test method you need new context and new repository because in this case they are isolated. But in your case they are not. Don't common context when you are testing common data. Also you have to remember to use 'using' keyword.

2021-01-03 19:16 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +        private Task<int> ClearUserProfileDbSet(IEnumerable<UserProfile> profilesToClear)
```suggestion
        private async Task<int> ClearUserProfileDbSet(IEnumerable<UserProfile> profilesToClear)
        {
            _dbContext.UserProfiles.RemoveRange(profilesToClear);
            return await _dbContext.SaveChangesAsync();
        }
```

2021-01-03 19:24 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            _dbContext.SaveChanges();
> async?

```suggestion
           public async Task GetAllMethodSimpleTest()
```

2021-01-03 19:39 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            Assert.That(() => _userProfileRepository.GetById(0), Throws.Exception);
> async

```suggestion
            Assert.That(async () => await _userProfileRepository.GetById(0), Throws.Exception);
```

2021-01-03 19:40 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            _dbContext.SaveChanges();
> async

```suggestion
           _dbContext.UserProfiles.AddRangeAsync(users);
            _dbContext.SaveChangesAsync();
```

2021-01-03 19:41 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            Assert.That(() => _userProfileRepository.GetById(notExistInDbIdentifier), Throws.Exception);
> async

```suggestion
           Assert.That(async () => await _userProfileRepository.GetById(notExistInDbIdentifier), Throws.Exception);
```

2021-01-03 19:43 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            Assert.AreEqual(1, allUsers.CountAsync().Result);
> await

```suggestion
           public async Task CreateMethodSimpleTest()
        {
            var userProfileToCreate = CreateTestUserProfile(3);
            await _userProfileRepository.Create(userProfileToCreate);
            _dbContext.SaveChanges();

            var allUsers = _userProfileRepository.GetAll();
            //Assert
            Assert.AreEqual(1, allUsers.CountAsync().Result);

            await ClearUserProfileDbSet(new List<UserProfile>() { userProfileToCreate });
        }
```

2021-01-03 19:47 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            Assert.IsTrue(!allUsersAfterDeleting.ContainsAsync(TestProfileToDelete).GetAwaiter().GetResult());
> async/await

```suggestion
           public async Task DeleteMethodSimpleTest()
        {
            // Arrange   
            var TestProfile = CreateTestUserProfile(4);
            var TestProfileToDelete = CreateTestUserProfile(5);

            var users = new List<UserProfile>()
                        {
                            TestProfile,
                            TestProfileToDelete
                        };

            await _dbContext.UserProfiles.AddRangeAsync(users);
            _dbContext.SaveChanges();

            _userProfileRepository.Delete(TestProfileToDelete.UserId);
            _dbContext.SaveChanges();

            var allUsersAfterDeleting = _userProfileRepository.GetAll();
            //Assert
            Assert.AreEqual(1, allUsersAfterDeleting.CountAsync().GetAwaiter().GetResult());
            Assert.IsTrue(!allUsersAfterDeleting.ContainsAsync(TestProfileToDelete).GetAwaiter().GetResult());

            users.Remove(TestProfileToDelete);
            await ClearUserProfileDbSet(users);
        }
```

2021-01-03 20:00 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +        private IRepository<UserProfile> _userProfileRepository;
> It is bad practice because in each test method you need new context and new repository because in this case they are isolated. But in your case they are not. Don't common context when you are testing common data. Also you have to remember to use 'using' keyword.

```suggestion
        private DIMSCoreContext _dbContext;
        private UserProfileRepository _userProfileRepository;
```

2021-01-03 20:19 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            _dbContext = new FakeDbContext().CreateFakeDbContextFactory();
> Use static keyword for method or move initialization of FaceDbContext in another variable.

```suggestion
             public static void Init()
        {
            _dbContext = new FakeDbContext().CreateFakeDbContextFactory();
            _userProfileRepository = new UserProfileRepository(_dbContext);
        }
```

2021-01-05 08:59 UTC, PushMeNow requested changes
Hi.
Still too many issues. Fix them and let me know.

2021-01-05 08:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            var _userProfileRepository = new UserProfileRepository(_dbContext);
It will be better if you create new test repository class and will initialize context there. Now it looks like pretty HUGE...

2021-01-05 08:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            _dbContext.UserProfiles.AddRange(users);
async

2021-01-05 08:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            await _dbContext.SaveChangesAsync();
Why do you need it??

2021-01-05 08:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            Assert.AreEqual(1, await allUsers.CountAsync());
Incorrect test. Need to check defined item.

2021-01-05 08:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            var userProfileToCreate = CreateTestUserProfile(3);
Need to move data initialization in common test repository class

2021-01-05 08:59 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            Assert.IsTrue(!allUsersAfterDeleting.ContainsAsync(TestProfileToDelete).Result);
You have to check defined item doesn't exist.
And remember about async

2021-01-05 11:38 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            Assert.AreEqual(1, await allUsers.CountAsync());
> Incorrect test. Need to check defined item.

```suggestion
            var allUsers = _userProfileRepository.GetAll();
            //Assert
            Assert.IsTrue(allUsers.ContainsAsync(userProfileToCreate).Result);
```

2021-01-05 11:40 UTC, ShlemenKirill commented on DIMS-Core/DIMS-Core.Tests/UserProfileRepositoryTests.cs
> +            Assert.IsTrue(!allUsersAfterDeleting.ContainsAsync(TestProfileToDelete).Result);
> You have to check defined item doesn't exist.
> And remember about async

```suggestion
            Assert.AreEqual(1, await allUsersAfterDeleting.CountAsync());
           Assert.IsFalse(await allUsersAfterDeleting.ContainsAsync(TestProfileToDelete));
```

2021-02-14 15:09 UTC, closed without merging