Andrey Gvozdev/create tables and vievs
Dev-incubator/DIMS-Core.Double pull request #3
Opened 2020-12-18 18:35 UTC by Andrey-Gvozdev

Create Task table

2020-12-21 17:43 UTC, ShlemenKirill requested changes

2020-12-21 17:43 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +	FROM Task
I think you should name each row in view

2020-12-21 17:48 UTC, Andrey-Gvozdev commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +	FROM Task
Why if the names are the same?

2020-12-21 17:50 UTC, ShlemenKirill requested changes

2020-12-21 17:50 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +	SELECT Task.TaskId FROM Task
Do you need to select TaskId from Task table?

2020-12-21 17:57 UTC, Andrey-Gvozdev commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +	SELECT Task.TaskId FROM Task
Yes, for comparison with the entered id

2020-12-21 17:58 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +	FROM Task
for better readability))

2020-12-21 17:58 UTC, Andrey-Gvozdev commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +	SELECT Task.TaskId FROM Task
> Do you need to select TaskId from Task table?

Could I have made it easier?

2020-12-21 18:01 UTC, ShlemenKirill commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +	SELECT Task.TaskId FROM Task
But you can delete task from table, without selecting data from table

2020-12-21 18:05 UTC, Andrey-Gvozdev commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +	SELECT Task.TaskId FROM Task
> You can delete task from table, without selecting data from table


I'm understood, thank

2020-12-21 18:17 UTC, PushMeNow requested changes
Hi dude.
Good job! I did some comments. Please resolve them and let me know.

2020-12-21 18:17 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/DIMS-Core.Database.refactorlog
> +</Operations>
What is the file? Why do you need it?

2020-12-21 18:17 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +	@localId int
Parameter name should be same with column name which he is related.

2020-12-21 18:17 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +	SELECT Task.TaskId FROM Task
Wait.. WUT?)) Could you use DELETE correctly)) https://www.w3schools.com/sql/sql_delete.asp

2020-12-21 18:17 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +	FROM Task
Agree with Kirill. In This case you have two case: 
1. You name columns without part 'Tast'
2. You have to name them by AS.
Here better first case because you don't have JOIN.

2020-12-21 18:22 UTC, Andrey-Gvozdev commented on DIMS-Core.Database/DIMS-Core.Database/Views/vTask.sql
> +	FROM Task
> Agree with Kirill. In This case you have two case:
> 
> 1. You name columns without part 'Tast'
> 2. You have to name them by AS.
>    Here better first case because you don't have JOIN.

Thank, I got it

2020-12-21 18:28 UTC, Andrey-Gvozdev commented on DIMS-Core.Database/DIMS-Core.Database/Procedures/DeleteTask.sql
> +	@localId int
> Parameter name should be same with column name which he is related.

I'm understood, thank

2020-12-21 18:41 UTC, ShlemenKirill requested changes
You use incorrect syntax of DELETE statement

2020-12-21 19:07 UTC, Andrey-Gvozdev reviewed
> You use incorrect syntax of DELETE statement

Changed)

2020-12-21 19:11 UTC, ShlemenKirill approved these changes

2020-12-21 21:33 UTC, ShlemenKirill approved these changes

2020-12-23 07:38 UTC, PushMeNow requested changes
Hi.
I did a comment. You have inaccuracy in types

2020-12-23 07:38 UTC, PushMeNow commented on DIMS-Core.Database/DIMS-Core.Database/Tables/Task.sql
> +    [Description] NCHAR(80) NOT NULL,
Usually need to use varchar or nvarchar types. Varchar are using if you are going to save English language only. But you have to prefer nvarchar because he is more flexible.

2020-12-23 09:22 UTC, Andrey-Gvozdev commented on DIMS-Core.Database/DIMS-Core.Database/Tables/Task.sql
> +    [Description] NCHAR(80) NOT NULL,
> Usually need to use varchar or nvarchar types. Varchar are using if you are going to save English language only. But you have to prefer nvarchar because he is more flexible.

Fixed)

2020-12-23 19:40 UTC, PushMeNow approved these changes
Approve

2020-12-23 19:45 UTC, merged