Repositories
Dev-incubator/DIMS-Core.Double pull request #8
Opened 2021-02-27 16:08 UTC by dbogdan2000

Created TaskRepository, UserTaskRepository, VTaskRepository and VUserTaskRepository. Implemented methods Create, Update and Delete in Repository. Added method DeleteUserProcedure to UserProfileRepository and method DeleteTaskProcedure to TaskRepository. This methods allow you to remove user or task by calling appropriate procedure.

2021-02-27 20:05 UTC, PushMeNow requested changes
Hi dude!
I did some comment. I hope you will figure them out. If not just let me know and I'll explain whole.

2021-02-27 20:05 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/UserProfileRepository.cs
>          }
Again about virtual keyword

2021-02-27 20:05 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/VTaskRepository.cs
> +        }
Don't duplicate logic. Look at Repository class and make up similar class for readonly repository.

2021-03-01 18:16 UTC, PushMeNow requested changes
Hi.
I did some comments. Let me know if any questions.

2021-03-01 18:16 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/TaskRepository.cs
> +            _context = context;
Repository already has the same object. If you need to get some prop from this object you have to create appropriate method.

2021-03-01 18:16 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/UserProfileRepository.cs
> +            _context = context;
Again don't duplicate objects

2021-03-03 20:04 UTC, PushMeNow requested changes
Hi man.
Need one small change

2021-03-03 20:04 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.DataAccessLayer/Repositories/Repository.cs
> +        protected DatabaseFacade GetDb()
Bad name. I don't understand what is doing this method so I have to look it through. I think GetDatabaseFacade will be better.

2021-03-04 05:55 UTC, PushMeNow approved these changes
Approved

2021-03-04 07:06 UTC, STALINovsky approved these changes
Looks nice, approved.

2021-03-05 19:42 UTC, merged