Add repositories and base infrastructure for unit testing
Dev-incubator/DIMS-Core.Double pull request #9
Opened 2021-02-27 20:57 UTC by STALINovsky

2021-02-28 21:02 UTC, PushMeNow requested changes
Hi!
I did some comments. Let me know if any questions.

2021-02-28 21:02 UTC, PushMeNow commented on DIMS-Core/DIMS-Core.Tests/DataAccessLayer/Infrastructure/TaskStateEqualityComparer.cs
> +    class TaskStateEqualityComparer : IEqualityComparer<TaskState>
Hmm... sorry what? Why do you need this class?

2021-03-01 18:08 UTC, PushMeNow approved these changes
Approved

2021-03-01 18:19 UTC, dbogdan2000 approved these changes

2021-03-03 19:56 UTC, merged